### ISSUE TITLE
Unrated doesn't work at all

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-1v1-arena#12]
When I queue for unrated it doesn't trigger but for rated it works fine.

Something's wrong :(

@XdevTLKWoW

**Comment by BarbzYHOOL** [comment]
Possible fix contained in this core patch https://cdn.discordapp.com/attachments/568503029532327937/672550579729596436/1v1_script.diff (thanks to Shard-MW)

**Comment by pangolp** [comment]
What is the current status of this issue, has it been resolved or does the problem persist? The module has had some updates, but I don't know if all the issues have been fixed. I look forward to hearing from you. Thank you.

**Comment by pangolp** [comment]
Greetings, by the date of publication of the issue, I would say that this issue is already resolved. If not, please reopen a new issue, attaching information so that we can solve the problem. Thank you very much.
