### ISSUE TITLE
Is there a way to NOT disable 5v5 arenas?

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-1v1-arena#13]
Just being curious

**Comment by peti446** [comment]
@BarbzYHOOL  Yes there is, but it requires some patching on the core side to create the 1v1 queue.However it has a drawback the 1v1 team will not appear in the UI where 5v5,3v3 and  2v2 is.
Also for old servers using this modules the 5v5 team composition would be needed to be migrated to 1v1 (changing the type from 5 to 1 on arena_team and in haracter_arena_stats from 2 to 3 (Assuming it was using the 5v5 braket for 1v1)). 

The patch for core can be found here: https://github.com/peti446/azerothcore-wotlk-1/commit/25ff91be4e2477114b2fe4e925183ae50a3ceb4c

And the patch for this module here: https://github.com/peti446/mod-1v1-arena/commit/6202352c918007b49e856ac3b64a5379270e9bff

This also fixes https://github.com/azerothcore/mod-1v1-arena/issues/12

Could do a PR in core if needed to add this functionality.

**Comment by Helias** [comment]
@peti446 what about to some PRs? :P

**Comment by peti446** [comment]
@Helias The core changes are used to creates a new queue for the 1v1, I am not aware to get this code into a module by itself.

All the custom code will only be in effect if the actual module is installed otherwise it will not compile it (usage of define "mod_1v1arena", similar to how eluna did it).

Kinda new to the project so, with more configurable, what is the scope here to get the changes allowed into the core?

**Comment by Helias** [comment]
I know that the way you modified the core does not affect the core itself if you do not use the arena 1v1 module, but, I think that there is an easy way to avoid that

We use that way only for important modules like Eluna or CFBG, for the others, we want to avoid this kind of code but only allow possible extension/module without using #ifdef / #define etc.

**Comment by pangolp** [comment]
What is the current status of this issue, has it been resolved or does the problem persist? The module has had some updates, but I don't know if all the issues have been fixed. I look forward to hearing from you. Thank you.

**Comment by pangolp** [comment]
Greetings, by the date of publication of the issue, I would say that this issue is already resolved. If not, please reopen a new issue, attaching information so that we can solve the problem. Thank you very much.
