### ISSUE TITLE
Not compatible with latest AzerothCore Version 

### ISSUE THREAD

**Issue by Meramaf** [azerothcore/mod-1v1-arena#22]
Since the last update, the module no longer works because the arena_type_1 no longer exists.

@Winfidonarleyan 

https://github.com/azerothcore/azerothcore-wotlk/commit/2b3d46bd4f52e8edf23ca77acca82ec51e9add08

**Comment by rogerc66** [comment]
It need an update, now if you initial a gossip with npc, it will crash the server.

**Comment by WillzDevs** [comment]
Really after the last update of the core, the module no longer works, when you start the conversation with the npc, the crash server

**Comment by FrancescoBorzi** [comment]
cc @UltraNix , not sure if it's related with your latest changes

**Comment by UltraNix** [comment]
@FrancescoBorzi No, it's not.

**Comment by WillzDevs** [comment]
it was right after the update, it stopped working, do you have to change anything in the module?

**Comment by Meramaf** [comment]
> it was right after the update, it stopped working, do you have to change anything in the module?

Nope, that's because of the hooks change in this commit.

https://github.com/azerothcore/azerothcore-wotlk/commit/2b3d46bd4f52e8edf23ca77acca82ec51e9add08

@Winfidonarleyan @FrancescoBorzi

**Comment by pangolp** [comment]
What is the current status of this issue, has it been resolved or does the problem persist? The module has had some updates, but I don't know if all the issues have been fixed. I look forward to hearing from you. Thank you.

**Comment by pangolp** [comment]
I just tested the module, with the latest version of AzerothCore, and this problem is no longer reproducible. In case you are using the latest version of the emulator and the module, and if the problem persists, please open a new issue, attaching information to fix the problem. Thank you.
