### ISSUE TITLE
Wrong Informations on SQL

### ISSUE THREAD

**Issue by mock7** [azerothcore/mod-1v1-arena#25]
NPC SQL into "creature_template" is completely wrong to the AzerothCore model, so u can't import because gonna show some error, i've tried put the NPC manually did worket but on worldserver show the error when i click on NPC:

FATAL: Unknown arena team type 1 for some arena team
Attempt get value from non-existed value field: 3041 (count: 1326) for object typeid: 4 type mask: 25

**Comment by Valoriaz** [comment]
I tried to reproduce your problem 

https://github.com/azerothcore/azerothcore-wotlk/blob/1638d1f951dd27b51e695de9c1d3e470e693faf2/src/server/game/Entities/Object/Object.h#L113
that the line why ur error code appear      
maybe  #22 

Maybe it will help the others and know why the error occurs

**Comment by Helias** [comment]
the creature_template structure has been changed, now we need to fix it here to make this module compatible with AzerothCore, the mod-npc-professions probably has the same issue.

this was caused by https://github.com/azerothcore/azerothcore-wotlk/pull/4359

**Comment by Valoriaz** [comment]
The SQL works fine now. but the same Object.h error

> 
> 
> I tried to reproduce your problem
> 
> https://github.com/azerothcore/azerothcore-wotlk/blob/1638d1f951dd27b51e695de9c1d3e470e693faf2/src/server/game/Entities/Object/Object.h#L113
> that the line why ur error code appear
> maybe #22
> 
> Maybe it will help the others and know why the error occurs

**Comment by Helias** [comment]
are you using the last version of AzerothCore?
