### ISSUE TITLE
SQL Problems 1v1_Battlemaster

### ISSUE THREAD

**Issue by WillzDevs** [azerothcore/mod-1v1-arena#27]
I'm still having problems applying the module's SQL, the error says that tables are missing...even adding the missing tables, the error continues, when you click on the npc the error and bring down the server

Can anyone help me?

**Comment by Helias** [comment]
are you using the last version of azerothcore?

**Comment by WillzDevs** [comment]
Yes

**Comment by rogerc66** [comment]
With the latest and ac and latest  1v1 arena, talk to npc still crash the server.
Error msg: 
fatal: unknown arena team type 1 for some arena team

**Comment by WillzDevs** [comment]
> With the latest and ac and latest 1v1 arena, talk to npc still crash the server.
> Error msg:
> fatal: unknown arena team type 1 for some arena team

This is exactly what is happening.

**Comment by Rastrian** [comment]
I will test this module but i think i know why its not working, the constants maybe are affecting with 5v5 arena(s).

constexpr uint32 ARENA_TEAM_1V1 = 1;constexpr uint32 ARENA_TYPE_1V1 = 1;

**Comment by WillzDevs** [comment]
> I will test this module but i think i know why its not working, the constants maybe are affecting with 5v5 arena(s).
> 
> constexpr uint32 ARENA_TEAM_1V1 = 1;constexpr uint32 ARENA_TYPE_1V1 = 1;

Thank you Rastrian! I'm waiting for your test, thanks and good night!

**Comment by pangolp** [comment]
What is the current status of this issue, has it been resolved or does the problem persist? The module has had some updates, but I don't know if all the issues have been fixed. I look forward to hearing from you. Thank you.

**Comment by pangolp** [comment]
I have just tested with the latest version of the emulator and the recent changes made in the module, so this problem should be solved. If not, please create a new issue, attaching information so we can check the bug.
