### ISSUE TITLE
Still not working Forbidden Talents!

### ISSUE THREAD

**Issue by svenbledt** [azerothcore/mod-1v1-arena#29]
As the title says. It's not Possible to forbid Spec's on the Config! Heal's and Tanks still able to join! 

Please Fix that ;) Thanks

**Comment by pangolp** [comment]
What is the current status of this issue, has it been resolved or does the problem persist? The module has had some updates, but I don't know if all the issues have been fixed. I look forward to hearing from you. Thank you.
