### ISSUE TITLE
 Row (unrated) [15$]

### ISSUE THREAD

**Issue by EricksOliveira** [azerothcore/mod-1v1-arena#3]
It's not calling for battle by getting in the (unrated) queue.

**Comment by milestorme** [comment]
I noticed that myself , confirmed

**Comment by Squeeezeee** [comment]
When you go to Battlemaster NPC and queue in for Unrated arena.
You are not getting a call for Unrated arena.
Unlike for Rated where you get call in 10-15 seconds.

Also you canont leave Queue by pressing Leave Queue at Battlemaster NPC, you have to click on Icon at Map to Leave queue.

**Comment by milestorme** [comment]
Bounty added $15 https://www.bountysource.com/issues/75230803-row-unrated thank you @Squeeezeee

**Comment by poszer** [comment]
Try this for leaving queue : 

https://github.com/poszer/mod-1v1-arena/commit/06635d2ac4d603daa8c5f18c1809ac9664aae80b

**Comment by Winfidonarleyan** [comment]
Try this, I no test, I test later

**Comment by Squeeezeee** [comment]
Leaving queue from Unrated/Rated ARENA.
FIXED by @poszer .
CONFIRMED AND TESTED.

**Comment by Winfidonarleyan** [comment]
For unrated arena need 10 characters, need change core if need 2 characters

**Comment by Squeeezeee** [comment]
Issued fixed by @poszer and tested on latest azerothcore build.
Please close issue.
