### ISSUE TITLE
No longer compiles with new build of Azerothcore

### ISSUE THREAD

**Issue by LannyE** [azerothcore/mod-1v1-arena#34]
[github/azerothcore-wotlk#10121](https://github.com/azerothcore/azerothcore-wotlk/pull/10121) commit breaks this module as the module uses the tokenizer code.

**Comment by LordArcanine** [comment]
/home/wow/azerothcore/modules/mod-1v1-arena/src/npc_arena1v1.cpp:44:9: error: unknown type name 'Tokenizer'
        Tokenizer toks(blockedTalentsStr, ',');

with lastest tc and lastest module

**Comment by pangolp** [comment]
What is the current status of this issue, has it been resolved or does the problem persist? The module has had some updates, but I don't know if all the issues have been fixed. I look forward to hearing from you. Thank you.

**Comment by pangolp** [comment]
I just compiled with the latest version of the emulator, so I close the issue. Try it and if anything, reopen a new issue with data to test and try to fix the bugs. Regards.
