### ISSUE TITLE
Crashes when leaving the arena

### ISSUE THREAD

**Issue by auguzsto** [azerothcore/mod-1v1-arena#40]
I was able to compile the module without errors. However, in the game, when entering the queue, finding opponent and entering the arena, if the player leaves the arena, "leave arena", the worldserer crashes.

Compiled in Ubuntu 20.04.

**Comment by Viskus** [comment]
It's a known error that people are working on, see here https://github.com/azerothcore/mod-1v1-arena/issues/38
There is also an active pull request with similar info here https://github.com/azerothcore/mod-1v1-arena/pull/39

**Comment by Helias** [comment]
closing for duplicate
