### ISSUE TITLE
It is impossible to start an arena with a rating

### ISSUE THREAD

**Issue by MegaserverRU** [azerothcore/mod-1v1-arena#43]
When you press the button:
Arena team clear
The arena becomes unavailable: Writes you are not a member of the 1v1 arena team
But the button to register the arena does not appear after clicking the Arena team clear button
![2022-09-16_10-50-00](https://user-images.githubusercontent.com/98691968/190586618-9d84c03f-fde6-40f7-9dd6-419efb1a6d7a.png)
![2022-09-16_10-50-22](https://user-images.githubusercontent.com/98691968/190586628-82ace917-7122-4331-9908-45eb376bcef6.png)
![2022-09-16_10-50-44](https://user-images.githubusercontent.com/98691968/190586631-d174129c-47d2-46c0-9047-4aeda2486216.png)

**Comment by qwe900** [comment]
Arena1v1.ArenaSlotID = 5

**Comment by Tony931023** [comment]
confirmed it is still happening, it is not possible to target rated arenas

**Comment by Torvahal** [comment]
i confirm, please fix.

**Comment by Tony931023** [comment]
@Winfidonarleyan can you check this

**Comment by huaijiuwow** [comment]
me too

**Comment by qwe900** [comment]
Sooo, Arena1v1, implaces slot1v1 3,  arenateam1v1 type 1 and max player 2, this is ok.
Then void Player::_LoadArenaTeamInfo() loads all arenateam info in memory in the PLAYER_FIELD_ARENA_TEAM_INFO_1_1 which has only place for 3 arena slots, due the change of max_slots to 4 which is done, the adress index for slot4 1v1 gets 1277 which is then PLAYER_FIELD_HONOR_CURRENCY thats why arenamod1v1 not work anymore

**Comment by pangolp** [comment]
What is the current status of this issue, has it been resolved or does the problem persist? The module has had some updates, but I don't know if all the issues have been fixed. I look forward to hearing from you. Thank you.

**Comment by Awixs777** [comment]
> What is the current status of this issue, has it been resolved or does the problem persist? The module has had some updates, but I don't know if all the issues have been fixed. I look forward to hearing from you. Thank you.

Tested today. The problem still persists. If the character has an honor, it is impossible to create a team. We'll be grateful for the fix.
[Video](https://drive.google.com/file/d/1SL7aDBE-3dZGI6C36r79dni3CQ7nET8T/view?usp=drive_link)

**Comment by pangolp** [comment]
Try updating the module, and see if you can now.
