### ISSUE TITLE
Bug: Configuration file function is invalid

### ISSUE THREAD

**Issue by zxnhrdz** [azerothcore/mod-1v1-arena#46]
### Current Behaviour

Creating a team can only be level 70， Arena1v1.MinLevel changes are not effective

### Expected Behaviour

The level requirement for creating a battlegroup should change with profile changes

### Steps to reproduce the problem

![image](https://github.com/azerothcore/mod-1v1-arena/assets/110412571/dc8da6d7-8866-45b2-acf7-d910efdb4eea)

### AC rev. hash/commit

[3eec04c]

### Operating system

Ubuntu 20.04

### Custom changes or Modules

Eluna

**Comment by pangolp** [comment]
Hi, you should try with the latest build that was made today, to see if it still fails, although I was not working with that exactly, but I did work on the module in general. Try it and let me know what happens.

**Comment by Helias** [comment]
it worked for me, I am closing this issue
