### ISSUE TITLE
Bug: Can't compile after AC commit 3fbded8

### ISSUE THREAD

**Issue by YggdrasilWotLK** [azerothcore/mod-1v1-arena#54]
### Current Behaviour

Re https://github.com/azerothcore/azerothcore-wotlk/commit/3fbded8f6bdaae1ec6897dae34afdab36b124899

### Expected Behaviour

Should compile just fine

### Steps to reproduce the problem

Git pull specified commit and 1v1 arena mod, then watch compile fail

### AC rev. hash/commit

Literally any rev with the specified commit

### Operating system

Any

### Custom changes or Modules

1v1 arena

**Comment by SilentJest3r** [comment]
![image](https://github.com/user-attachments/assets/2805dba1-96be-41c6-9afa-de80a8b6fcda)

**Comment by Helias** [comment]
fixed by https://github.com/azerothcore/mod-1v1-arena/pull/53
update to latest version and try again
